interface IFlag {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
  BAD_REQUEST: 'BAD_REQUEST',
}

export const flag: IFlag = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
}